### ISSUE TITLE
npm start : return error

### ISSUE THREAD

**Issue by mastermoin** [nikospara/angular-require-lazy#3]
after npm install - npm start will return following error log

0 info it worked if it ends with ok
1 verbose cli [ 'c:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'c:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose stack Error: missing script: start
4 verbose stack     at run (c:\Program Files (x86)\nodejs\node_modules\npm\lib\run-script.js:165:19)
4 verbose stack     at c:\Program Files (x86)\nodejs\node_modules\npm\lib\run-script.js:81:5
4 verbose stack     at c:\Program Files (x86)\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:52:40
4 verbose stack     at c:\Program Files (x86)\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:376:33
4 verbose stack     at checkBinReferences_ (c:\Program Files (x86)\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:341:59)
4 verbose stack     at final (c:\Program Files (x86)\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:373:17)
4 verbose stack     at then (c:\Program Files (x86)\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:127:33)
4 verbose stack     at c:\Program Files (x86)\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:267:40
4 verbose stack     at evalmachine.<anonymous>:334:14
4 verbose stack     at c:\Program Files (x86)\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:102:5
5 verbose cwd c:\users\emoimas\Downloads\angular-require-lazy-master (1)\angular-require-lazy-master
6 error Windows_NT 6.1.7601
7 error argv "c:\\Program Files (x86)\\nodejs\\node.exe" "c:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
8 error node v0.12.2
9 error npm  v2.7.4
10 error missing script: start
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

**Comment by nikospara** [comment]
Hello, and thanks for the feedback.

Indeed it will throw *because it is not designed to run with `npm start`*.

Use `node app.js`, as per the README file instead and point a browser to http://localhost:8110/app.html (see [README.md#Run](https://github.com/nikospara/angular-require-lazy#run)).

Please let me know if I misunderstood your use case.

**Comment by mastermoin** [comment]
hey thanks for reply but still on browser i  am  getting these errors 

GET http://localhost:8110/scripts/lib/less.js/dist/less-1.6.2.js 
app.html:35 
GET http://localhost:8110/scripts/lib/requirejs/require.js 
app.html:36 
GET http://localhost:8110/scripts/lib/jquery/dist/jquery.js 
app.html:39 
Uncaught ReferenceError: jQuery is not defined(anonymous function) @ app.html:39

**Comment by nikospara** [comment]
Yes, I confirm that and it is caused by 2 reasons:

1. I had forgotten to mention that you need to run `bower install` in the build instructions (fixed); please make sure you have run `bower install` *after* `npm install`!
2. This is using an old version of Bootstrap(*), which is obviously not compatible with LESS 2.x; fixated versions of LESS-related plugins

(*) It would be nice to use more recent versions, but since the scope of this project is not to demonstrate a state-of-the-art build system or UI, but rather to explore a way of integrating Angular+Require with lazy loading, I will not change it. For production systems, use the latest versions, install Bootstrap through Bower etc...

Thanks again for the valuable input!
